/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-tertiary-fixed": "#131b2e",
        "on-primary-container": "#dad7ff",
        "secondary-fixed": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "surface-tint": "#4d44e3",
        "background": "#f7f9fb",
        "on-tertiary-container": "#d4dbf5",
        "primary-container": "#4f46e5",
        "surface-variant": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "inverse-surface": "#2d3133",
        "on-background": "#191c1e",
        "secondary-fixed-dim": "#b7c8e1",
        "secondary-container": "#d0e1fb",
        "tertiary": "#41485e",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#bec6e0",
        "on-secondary-container": "#54647a",
        "surface-container-high": "#e6e8ea",
        "tertiary-container": "#586076",
        "surface": "#f7f9fb",
        "on-primary-fixed-variant": "#3323cc",
        "secondary": "#505f76",
        "outline": "#777587",
        "primary-fixed": "#e2dfff",
        "surface-container": "#eceef0",
        "surface-bright": "#f7f9fb",
        "outline-variant": "#c7c4d8",
        "tertiary-fixed": "#dae2fd",
        "on-surface-variant": "#464555",
        "on-secondary-fixed-variant": "#38485d",
        "on-surface": "#191c1e",
        "on-tertiary-fixed-variant": "#3f465c",
        "inverse-primary": "#c3c0ff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#c3c0ff",
        "on-primary-fixed": "#0f0069",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "primary": "#3525cd",
        "surface-container-highest": "#e0e3e5",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#0b1c30"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "margin-mobile": "16px",
        "gutter": "24px",
        "lg": "24px",
        "md": "16px",
        "unit": "4px",
        "xxl": "64px",
        "xs": "4px",
        "container-max": "1280px",
        "xl": "40px",
        "sm": "8px"
      },
      "fontFamily": {
        "sans": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Geist", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "mono-sm": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "headline-sm": ["18px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "mono-sm": ["13px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
